# Generated by Django 4.2 on 2023-05-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
        ('cart', '0003_cart_price'),
    ]

    operations = [
    ]
