# Generated by Django 4.2 on 2023-05-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
        ('user', '0005_remove_account_user_user_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
