# Generated by Django 4.2 on 2023-05-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_account_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
