# Generated by Django 4.2 on 2023-05-09 22:00

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='drink/default.png', upload_to='drink/')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsCandy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='/toppings/candy/default.png', upload_to='toppings/candy/')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='/toppings/fruit/default.png', upload_to='toppings/fruit/')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsSauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='/toppings/sauces/default.png', upload_to='toppings/sauces/')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(default='/pizza/default.png', upload_to='pizza/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.pizzacategory')),
                ('toppings_candy', models.ForeignKey(default=menu.models.ToppingsCandy, on_delete=django.db.models.deletion.CASCADE, to='menu.toppingscandy')),
                ('toppings_fruit', models.ForeignKey(default=menu.models.ToppingsFruit, on_delete=django.db.models.deletion.CASCADE, to='menu.toppingsfruit')),
                ('toppings_sauces', models.ForeignKey(default=menu.models.ToppingsSauces, on_delete=django.db.models.deletion.CASCADE, to='menu.toppingssauces')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drink')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
        ),
    ]
