# Generated by Django 4.2 on 2023-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingscandy',
            name='image',
            field=models.ImageField(default='/toppingscandy/default.png', upload_to='toppingscandy/'),
        ),
        migrations.AddField(
            model_name='toppingsfruit',
            name='image',
            field=models.ImageField(default='/toppingsfruit/default.png', upload_to='toppingsfruit/'),
        ),
        migrations.AddField(
            model_name='toppingssauces',
            name='image',
            field=models.ImageField(default='/toppingssauces/default.png', upload_to='toppingssauces/'),
        ),
    ]
