# Generated by Django 4.2 on 2023-05-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_image_to_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
