# Generated by Django 4.2 on 2023-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='drink/default.png', upload_to='drink/'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='pizza/default.png', upload_to='pizza/'),
        ),
        migrations.AlterField(
            model_name='drinkimage',
            name='image',
            field=models.ImageField(max_length=9999, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizzaimage',
            name='image',
            field=models.ImageField(max_length=9999, upload_to=''),
        ),
    ]
