# Generated by Django 4.2 on 2023-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_image_to_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
