# Generated by Django 4.2 on 2023-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_toppingscandy_image_toppingsfruit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppingscandy',
            name='image',
            field=models.ImageField(default='/toppings/candy/default.png', upload_to='toppings/candy/'),
        ),
        migrations.AlterField(
            model_name='toppingsfruit',
            name='image',
            field=models.ImageField(default='/toppings/fruit/default.png', upload_to='toppings/fruit/'),
        ),
        migrations.AlterField(
            model_name='toppingssauces',
            name='image',
            field=models.ImageField(default='/toppings/sauces/default.png', upload_to='toppings/sauces/'),
        ),
    ]
