# Generated by Django 4.2 on 2023-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_drink_image_pizza_image_alter_drinkimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
