# Generated by Django 4.2 on 2023-05-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pizza_toppings_delete_pizzatoppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.drink'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
