# Generated by Django 4.2 on 2023-05-11 12:32

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(default=menu.models.Toppings, on_delete=django.db.models.deletion.CASCADE, to='menu.toppings'),
        ),
    ]
