# Generated by Django 4.2 on 2023-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_offer_drink_alter_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredient',
        ),
    ]
