# Generated by Django 4.2 on 2023-05-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_pizza_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzaimage',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='DrinkImage',
        ),
        migrations.DeleteModel(
            name='PizzaImage',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.toppings'),
        ),
    ]
