# Generated by Django 4.2 on 2023-05-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_drink_size_remove_pizza_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='drink',
        ),
    ]
