# Generated by Django 4.2 on 2023-05-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_toppings_remove_pizzaimage_pizza_delete_drinkimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu.pizzacategory'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu.toppings'),
        ),
    ]
