# Generated by Django 4.2 on 2023-05-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_pizza_category_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.pizzacategory'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(default=menu.models.Toppings, on_delete=django.db.models.deletion.CASCADE, to='menu.toppings'),
        ),
    ]
