# Generated by Django 4.2 on 2023-05-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_toppings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={},
        ),
    ]
