# Generated by Django 4.2 on 2023-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_toppings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.CharField(blank=True, choices=[('Fruity', 'Fruity'), ('Vegan', 'Vegan'), ('Popular', 'Popular')], max_length=10, null=True),
        ),
    ]
