# Generated by Django 4.2 on 2023-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_category_alter_pizza_options_remove_pizza_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='categories',
            field=models.ManyToManyField(blank=True, to='menu.category'),
        ),
    ]
